question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Science: Computers",
     "question": "Linus Torvalds created Linux and Git.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Windows 7 operating system has six main editions.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Ada Lovelace is often considered the first computer programmer.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
     "question": "Time on Computers is measured via the EPOX System.",
     "correct_answer": "False", "incorrect_answers": ["True"]}
]

sports_data = [
     {"type": "boolean",
      "difficulty": "medium",
      "category": "Sports",
      "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
      "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
      "question": "The Olympics tennis court is a giant green screen.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"type": "boolean", "difficulty": "easy", "category": "Sports",
      "question": "There are a total of 20 races in Formula One 2016 season.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "easy", "category": "Sports",
      "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
      "question": "Skateboarding was included in the 2020 Summer Olympics in Tokyo.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"type": "boolean", "difficulty": "easy", "category": "Sports",
      "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "easy", "category": "Sports",
      "question": "Peyton Manning retired after winning Super Bowl XLIX.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
      "question": "Tennis was once known as Racquetball.", "correct_answer": "False",
      "incorrect_answers": ["True"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
      "question": "ATP tennis hosted several tournaments on carpet court before being replaced to reduce injuries.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"type": "boolean", "difficulty": "medium", "category": "Sports",
      "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.",
      "correct_answer": "True", "incorrect_answers": ["False"]}
]
